Sending build context to Docker daemon  57.86kB
Step 1/9 : FROM debian:stretch
 ---> 3bbb526d2608
Step 2/9 : RUN apt-get update
 ---> Using cache
 ---> d14cf94de60b
Step 3/9 : RUN apt-get -y install git curl
 ---> Using cache
 ---> c32561947ae4
Step 4/9 : RUN curl https://dl.google.com/go/go1.11.linux-amd64.tar.gz | tar xz -C /usr/local
 ---> Using cache
 ---> c8b18e232b4d
Step 5/9 : ENV GOPATH="$HOME/go"
 ---> Using cache
 ---> 159a829ef9b4
Step 6/9 : ENV PATH="${PATH}:/usr/local/go/bin:$GOPATH/bin"
 ---> Using cache
 ---> d8aa220269f1
Step 7/9 : ENV HOME="/root"
 ---> Using cache
 ---> a52ff99647e4
Step 8/9 : WORKDIR $HOME
 ---> Using cache
 ---> f586f86b9046
Step 9/9 : RUN go get github.com/goreleaser/goreleaser
 ---> Running in 09d5eeb362af
Removing intermediate container 09d5eeb362af
 ---> 0cf7208395be
Successfully built 0cf7208395be
Successfully tagged go-issue-27706-1:latest
