FROM debian:stretch

RUN apt-get update
RUN apt-get -y install git curl

# go - install
RUN curl https://dl.google.com/go/go1.11.linux-amd64.tar.gz | tar xz -C /usr/local
ENV GOPATH="$HOME/go"
ENV PATH="${PATH}:/usr/local/go/bin:$GOPATH/bin"

# home
ENV HOME="/root"

# working directory
WORKDIR $HOME

# install goreleaser
RUN cd $HOME && go mod init github.com/hello/world && go get github.com/goreleaser/goreleaser
